export const frontendConfig = Object.freeze({
  appTitle: 'True Robotics FedEx Shipping',
  githubPagesBase: '/TrueRoboticsFedexShippingApp/',
  apiBaseUrl: 'http://localhost:8787',
  addressAutocompleteUrl: 'https://nominatim.openstreetmap.org/search',
  enableMockSubmission: false,
  logoUrl: 'logo.png',
});

export const serverConfig = Object.freeze({
  port: 8787,
  host: '127.0.0.1',
  allowedOrigin: 'http://localhost:5173',
  fedexEnableMock: false,
  fedexApiBaseUrl: 'https://apis-sandbox.fedex.com',
  shipperName: 'True Robotics',
  shipperEmail: 'info@truerobotics.org',
  shipperPhone: '7742769866',
  shipperAddress1: '49 Canterbury St',
  shipperAddress2: 'STE 700',
  shipperCity: 'Worcester',
  shipperState: 'MA',
  shipperPostalCode: '01609',
  shipperCountryCode: 'US',
  pickupType: 'DROPOFF_AT_FEDEX_LOCATION',
  weightUnits: 'LB',
  packageWeightValue: 10,
  labelImageType: 'PDF',
  labelStockType: 'PAPER_4X6',
  labelFormatType: 'COMMON2D',
  debugLabels: false,
});
